/*
 * Copyright (C) 2015  Hugo Freire Gil
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 */

package com.abajar.avleditor.jsbsim

import com.abajar.avleditor.crrcsim.CRRCSim
import com.abajar.avleditor.avl.runcase.AvlCalculation
import com.abajar.avleditor.ac3d.AC3DWriter
import java.io.{File, PrintWriter}
import JsbsimWriter._

/**
 * Assembles a FlightGear-flyable aircraft package so the exported JSBSim model can
 * be piloted with a 3D view:
 * {{{
 *   <root>/<name>/
 *     <name>-set.xml     top-level FlightGear config (fdm = jsb, FlightGear's name for JSBSim)
 *     <name>.xml         the JSBSim FDM
 *     Engines/           motor and propeller files (if any)
 *     Models/<name>.ac   AC3D visual mesh from the AVL geometry
 * }}}
 * Fly with:  `fgfs --fg-aircraft=<root> --aircraft=<name>`
 *
 * `/sim/model/path` is resolved by FlightGear relative to the aircraft's own directory,
 * so it stays a bare `Models/<name>.ac`. Prefixing it with the package name makes
 * FlightGear log "Failed to find aircraft model" and fall back to glider.ac.
 */
object FlightGearExporter {

  def export(rootDir: File, name: String, crrcsim: CRRCSim, calc: AvlCalculation): Unit = {
    val ac = JsbsimExporter.buildAircraft(name, crrcsim, calc)
    val model = generate(ac)
    val dir = new File(rootDir, name)

    write(new File(dir, s"$name.xml"), model.aircraftXml)
    model.engineFiles.foreach { case (fn, content) => write(new File(dir, s"Engines/$fn"), content) }
    val geo = crrcsim.getAvl.getGeometry
    write(new File(dir, s"Models/$name.ac"), AC3DWriter.fromGeometry(geo))
    write(new File(dir, s"$name-set.xml"), setXml(name, AC3DWriter.boundsFromGeometry(geo)))
  }

  /** FlightGear's identifier for the JSBSim FDM. Not "jsbsim": anything outside FlightGear's
    * table (jsb, yasim, larcsim, ufo, magic, balloon, external, null) is rejected at startup
    * with "Unrecognized flight model '...', cannot init flight dynamics model". */
  private[jsbsim] val FlightModel = "jsb"

  /**
   * FlightGear's external "Chase View". Generated models have no cockpit interior, so starting
   * in the default cockpit view (0) puts the camera inside the airframe and shows an empty
   * scene — the aircraft appears to be missing. Passing this on the command line does not work:
   * `--prop:` is applied before FlightGear builds its views.
   */
  private[jsbsim] val ChaseView = 2

  /**
   * Camera distance derived from the mesh's own bounding box. FlightGear's default chase
   * distance is 25 m, which turns a 2 m model into a speck; stock aircraft are ten times
   * bigger. Offsets are in the model frame: +x right, +y up, +z aft.
   *
   * Note: this does NOT fix "the aircraft is not visible in FlightGear" — see PLAN.md. With a
   * stock FlightGear model substituted into this package the camera stays glued to the
   * aircraft too, so the cause is elsewhere in the package, not in the mesh or this distance.
   */
  private[jsbsim] final case class ViewGeometry(eyeUp: Double, eyeAft: Double, chaseDistance: Double)

  private[jsbsim] def viewGeometry(
      bounds: Option[((Float, Float, Float), (Float, Float, Float))]): ViewGeometry =
    bounds match {
      case Some(((_, minUp, minAft), (_, maxUp, maxAft))) =>
        val length = math.max(maxAft - minAft, 0.1)
        val height = math.max(maxUp - minUp, 0.05)
        // Eye just above the top of the airframe, a quarter of the length behind the nose.
        ViewGeometry(maxUp + 0.1 * height, minAft + 0.25 * length, math.max(6.0, 5.0 * length))
      case None =>
        ViewGeometry(0.5, 0.0, 10.0)
    }

  private[jsbsim] def setXml(
      name: String,
      bounds: Option[((Float, Float, Float), (Float, Float, Float))] = None): String = {
    val view = viewGeometry(bounds)
    f"""<?xml version="1.0"?>
    |<PropertyList>
    |  <sim>
    |    <current-view>
    |      <view-number type="int">$ChaseView</view-number>
    |    </current-view>
    |    <description>$name (generated by AVL Editor)</description>
    |    <author>AVL Editor</author>
    |    <flight-model>$FlightModel</flight-model>
    |    <aero>$name</aero>
    |    <model>
    |      <path>Models/$name.ac</path>
    |    </model>
    |    <chase-distance-m archive="y">${-view.chaseDistance}%.3f</chase-distance-m>
    |  </sim>
    |</PropertyList>
    |""".stripMargin
  }

  private def write(f: File, content: String): Unit = {
    Option(f.getParentFile).foreach(_.mkdirs())
    val pw = new PrintWriter(f)
    try pw.write(content) finally pw.close()
  }
}
