/*
 * Copyright (C) 2015  Hugo Freire Gil
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 */

package com.abajar.avleditor.jsbsim

import com.abajar.avleditor.crrcsim.CRRCSim
import com.abajar.avleditor.avl.runcase.AvlCalculation
import com.abajar.avleditor.ac3d.AC3DWriter
import java.io.{File, PrintWriter}
import JsbsimWriter._

/**
 * Assembles a FlightGear-flyable aircraft package so the exported JSBSim model can
 * be piloted with a 3D view:
 * {{{
 *   <root>/<name>/
 *     <name>-set.xml     top-level FlightGear config (fdm = jsbsim)
 *     <name>.xml         the JSBSim FDM
 *     Engines/           motor and propeller files (if any)
 *     Models/<name>.ac   AC3D visual mesh from the AVL geometry
 * }}}
 * Fly with:  `fgfs --fg-aircraft=<root> --aircraft=<name>`
 */
object FlightGearExporter {

  def export(rootDir: File, name: String, crrcsim: CRRCSim, calc: AvlCalculation): Unit = {
    val ac = JsbsimExporter.buildAircraft(name, crrcsim, calc)
    val model = generate(ac)
    val dir = new File(rootDir, name)

    write(new File(dir, s"$name.xml"), model.aircraftXml)
    model.engineFiles.foreach { case (fn, content) => write(new File(dir, s"Engines/$fn"), content) }
    write(new File(dir, s"Models/$name.ac"), AC3DWriter.fromGeometry(crrcsim.getAvl.getGeometry))
    write(new File(dir, s"$name-set.xml"), setXml(name))
  }

  private def setXml(name: String): String =
    s"""<?xml version="1.0"?>
    |<PropertyList>
    |  <sim>
    |    <description>$name (generated by AVL Editor)</description>
    |    <author>AVL Editor</author>
    |    <flight-model>jsbsim</flight-model>
    |    <aero>$name</aero>
    |    <model>
    |      <path>Models/$name.ac</path>
    |    </model>
    |  </sim>
    |</PropertyList>
    |""".stripMargin

  private def write(f: File, content: String): Unit = {
    Option(f.getParentFile).foreach(_.mkdirs())
    val pw = new PrintWriter(f)
    try pw.write(content) finally pw.close()
  }
}
